config/routes.rb
Maintr::Application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  as :user do
    get 'users/edit_password' => 'registrations#edit_password', :as => 'edit_user_password_registration'    
    patch 'users/:id' => 'registrations#update_password', :as => 'user_password_registration'            
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  

  root to: 'pages#front'
  get '/settings', to: 'settings#show'
  get '/dashboard', to: 'reminders#dashboard'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  get 'sites/remindee_option', to: 'sites#remindee_option'  #for the ajax request from sites form
  get '/confirm/:id', to: 'reminder_histories#url_redirect'
  match "/sms_back.json", to: 'reminder_histories#sms_back', via: [:get, :post], defaults: {format: 'json'}
  get '/dashboard_update', to: 'reminders#dashboard_update'  #for ajax call to update dashboard
  namespace :reminders do
    resources :items, only: [:index]
  end

  resources :sites do
    resources :items, only: [:index, :show, :destroy]

  end

  resources :item_units

  resources :custom_items, only: [:new, :create, :destroy]
  resources :custom_tasks, only: [:new, :create, :destroy]
  resources :remindees, only: [:new, :create, :edit, :update, :destroy]
  resources :reminders, only: [ :new, :create, :edit, :update] do
    post :state
  end

  resources :reminder_histories, only: [:index, :show], as: :histories
  get '/rh_events.json', to: 'reminder_histories#events', defaults: {format: 'json'}  #to pass reminder history data to calendar
  resources :reminder_histories,  only: [:show] do
    member do
      post :complete
      get :reminder_updated
      get :confirm
    end
  end

  
  
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  

end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  include TimeInterval
  include ViewHelper
FREQUENCY = {
  1 => "every day",
  2 => "once a week",
  3 => "every 2 weeks",
  4 => " once a month",
  5 => " 2 months",
  6 => "3 months",
  7 => "6 months",
  8 => "once a year"
}

REMIND_BEFORE = {
  1 => "every day",
  2 => "a day before",
  3 => "2 days before",
  4 => "one week before",
  5 => "2 weeks before",
  6 => "3 weeks before",
  7 => "one month before"
} 
  
  REMINDER_TIME = {hour: 9, min: 0, sec: 0}

  belongs_to :item_unit_task

  has_many :reminder_remindees, dependent: :destroy
  has_many :remindees, through: :reminder_remindees

  has_many :reminder_histories, dependent: :destroy

  validates :due_date,  presence: true
  #validates_presence_of :remindees, :message => "Atleast one notification recipient is to be selected"
  validate :remindees_presence 
  validate :remind_before_less_than_frequency
  
  def self.send_reminders
    d = Date.today.in_time_zone("UTC")
    @reminders = Reminder.where(reminder1: d.beginning_of_day..d.end_of_day, is_active?: true).all
    @reminders.each do |r|
       
      r.remindees.each do |rem|
        offset = (r.reminder1 - d.beginning_of_day)/3600
        #offset = (r.reminder1 - Time.now.utc)/3600
        ReminderJob.perform_later(r, rem, offset.to_f)  #sends emails
       
        if rem.phone
          rh = r.reminder_histories.last
          path = ConfirmPath.where(remindee_id: rem.id, reminder_history_id: rh.id ).first
          SmsReminderJob.set(wait: offset.to_f.hours).perform_later(r, rem, path)  #sends sms
          

        end
      end
    end
  end

  def self.due_date_index

  end

  
  def task
    get_task_object(self.item_unit_task.task).title
  end

  def description
    get_task_object(self.item_unit_task.task).description
  end

  def site
    self.reminder_histories.first.site if self
  end
  def item_unit
    self.item_unit_task.item_unit.name
  end


  def item
    get_item_object(self.item_unit_task.item_unit.item).name
  end



  private
  def remind_before_less_than_frequency
    freq = self.get_freq(frequency_choice)
    remind1 = self.get_remind_before(reminder1_choice)

    errors.add(:frequency, "should be greater than 'Send reminder' time interval" ) if freq < remind1

  end

  def remindees_presence
    errors.add(:base, "Atleast one notification recipient should be selected" ) if self.remindees.blank?


  end

  
 
  
end

app/controllers/reminders/items_controller.rb
class Reminders::ItemsController < ApplicationController
  before_action :authenticate_user!


  def index
    #come here when Reminder on the nav bar is clicked   

    @site = current_user.sites.first 
    @items = Item.all.where(site_id: @site.id)
    @item = Item.where(itemable_type: "SystemItem", site_id: @site.id).first
    #binding.pry
    render 'sites/items/index'
  end


end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :authenticate_user!
  include TimeInterval
  helper_method TimeInterval.instance_methods


  def new
    @item_unit_task = ItemUnitTask.find params[:iut_id]
    @site = $current_site
    #@site = Site.find @item_unit_task.item_unit.site_id
    @reminder = Reminder.new
   
  end

 def create
  
  create_update_reminder 
  
   @reminder.remindees << @remindees

  if @reminder.save
    
    
    #@remindees.each do |r|
    #  ReminderRemindee.create(reminder_id: @reminder.id, remindee_id: r.id)
    #end
    create_reminder_history
  end

 end

 def edit
  #binding.pry
  @reminder = Reminder.find params[:id]
  @item_unit_task = ItemUnitTask.find @reminder.item_unit_task_id
  item_unit = @item_unit_task.item_unit
  @site = Site.find item_unit.site_id
  #binding.pry
 end

 def update
  @reminder = Reminder.find params[:id]
  create_update_reminder 
  
   last_reminder_history = @reminder.reminder_histories.last  #if the reminder due date gets changed on editing.  check if task was complete in history
    unless last_reminder_history.complete 
      last_reminder_history.update(due_date: @reminder.due_date) 
      last_reminder_history.remindees = @reminder.remindees.present? ? @reminder.remindees : [] 
    end
 end

   def state
    
    @reminder = Reminder.find params[:reminder_id]

    switch = !@reminder.is_active?
    @reminder.update(is_active?: switch)

   end

 
  def dashboard
    #@pie_chart_data = []
    if current_user.sites.blank?
      redirect_to settings_path

    end

      @reminder_histories = ReminderHistory.includes(:site).where(site: current_user.sites).order("due_date DESC")
   
      dat = ReminderHistory.where(site: current_user.sites).group_by_day(:state, "count", "*")
      #binding.pry
      @reminder_histories.each do |rh|
        #@pie_chart_data << rh.reminder.item

      end
      @display = "all"
   
  end

  def dashboard_update
    site = params[:site_name].downcase
    if site == "all"
      reminder_histories = ReminderHistory.includes(:site).where(site: current_user.sites)
    
    else
      site = Site.find_by_name(site)
      reminder_histories = ReminderHistory.includes(:site).where(site: site)
     
    end
    response = dashboard_data_prep reminder_histories
    respond_to do |format|
      format.json {render json: {response: response}}
    end

  end

 



 private

 def dashboard_data_prep reminder_histories
  response = Array.new
  hash = {}
    
  reminder_histories.each do |rh|
      r = rh.reminder
        hash = {:location => rh.site.name.titleize, :unit => "#{r.item}: #{r.item_unit}", :task => r.task,
          :due_date => rh.due_date.in_time_zone(r.site.time_zone).strftime("%a, %d %b"),:state => rh.state }
          
          hash = hash.merge({:completed_on => (rh.complete ? rh.completion_date.in_time_zone(r.site.time_zone).strftime("%a, %d %b") : "")})  
          hash = hash.merge({:completed_by => (rh.complete ? rh.completed_by.name : "")})
    response << hash

  end
  response
 end

 def create_update_reminder 
  Time.zone = $current_site.time_zone
  iut_id = params[:reminder][:item_unit_task_id]
  @item_unit_task = ItemUnitTask.find iut_id
    
  f = params[:reminder][:frequency] 
  freq = get_freq(f)                          #gets the actual time duration for frequency
  due_date_string = params[:reminder][:due_date] 
  #due = (get_due_date due_date_string).in_time_zone if !due_date_string.blank?   # returns Date
  due = Time.zone.parse(due_date_string) if !due_date_string.blank?   # returns Date


  reminder1_choice = params[:reminder][:reminder1]  #String
  
  if !due_date_string.blank?
  remind_before1 = due - get_remind_before(reminder1_choice)  #Active.Support::TimeWithZone
  remind_before1 = remind_before1.change(Reminder::REMINDER_TIME)   #reminder_time set to 9 AM local
  end

  @remindees = get_remindees params[:reminder][:remindee_ids]

  if @reminder
    @reminder.remindees = @remindees.present? ? @remindees : []
    @reminder.update_attributes(frequency: freq, frequency_choice: f, due_date: due, reminder1_choice: reminder1_choice, reminder1: remind_before1)
    create_confirm_paths @reminder, @reminder.reminder_histories.last    
  else
    @reminder = Reminder.new(frequency: freq, frequency_choice: f, due_date: due, reminder1_choice: reminder1_choice, reminder1: remind_before1, item_unit_task_id: @item_unit_task.id )
  end
 
  
 
 end

 

 def reminder_params
    params.require(:reminder).permit(:frequency,:frequency_choice, :due_date, :reminder1, :reminder2, :item_unit_task_id)
 end 

  def get_due_date due
    #binding.pry
    DateTime.strptime(due, '%Y-%m-%d')  #convert from string to Date class
  end 

 

 def create_reminder_history
    history = ReminderHistory.create(due_date: @reminder.due_date.in_time_zone, reminder_id: @reminder.id, site_id: $current_site.id)
    history.remindees = @reminder.remindees
    @reminder.remindees.each do |remindee|
      ReminderMailer.reminder_created(@reminder, remindee).deliver_later!(wait: 10.seconds)
      send_intro_sms @reminder, remindee
    end
    create_confirm_paths @reminder, history
 end

 def send_intro_sms reminder, remindee
  RestClient.get 'https://api.tropo.com/1.0/sessions', {:params => {
          :action => 'create', 
          :token => ENV["tropo_sms_token"], 
          :numbertodial => remindee.phone, 
          :msg => " #{remindee.name}, you have been added by #{current_user.username} to receive reminders for #{reminder.task} for #{reminder.item}. Check email for details."}}
 end


 def create_confirm_paths reminder, history

  history.confirm_paths.destroy_all if history
  reminder.remindees.each do |remindee|
   path = confirm_reminder_history_path(history.token, remindee_id: remindee.id)
   ConfirmPath.create(confirm_path: path, reminder_history_id: history.id, remindee_id: remindee.id)
  end
 end

 def get_remindees a

    a.reject! {|i| i.empty?}
    return Remindee.where(id: a)
 end
 
 

 
  
end

app/helpers/reminders/items_helper.rb
module Reminders::ItemsHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_dashboard_sites_dropdown.html.haml
#dashboard-dropdown.dropdown.pull-left
  -if current_user.sites.count == 1
    = current_user.sites.first.name.titleize
  -else
    %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button", :id=> "site-display" }
      = @display.titleize
      %span.caret
    %ul.dropdown-menu{:role => "menu", :id => "dashboard-site-select"}
      %li
        =link_to "All", '#'  
      - current_user.sites.each do |site|
        %li
          =link_to site.name.titleize, '#' 
        

app/views/reminders/_edit.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h4#myModalLabel.modal-title= "Editing reminder for #{get_item_object(iut.item_unit.item).name.titleize} unit #{iut.item_unit.name.titleize}"
    =render 'reminders/reminder_form', iut: iut  

app/views/reminders/_new.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h4#myModalLabel.modal-title= "Adding reminder for #{get_item_object(iut.item_unit.item).name.titleize} unit #{iut.item_unit.name.titleize}"
    =render 'reminders/reminder_form', iut: iut  

app/views/reminders/_reminder.html.haml
-reminder = iut.reminder
=render 'reminders/reminder_nav', reminder: reminder   
#reminder-display
  %table.reminder-display
    %thead
      %tr
        %th= "Every"
        %th= "Due"
        %th= "Notify"
        %th= "Remind on"
    %tbody
      %tr
        %td= "#{get_frequency_choice reminder.frequency_choice.to_i}"
        %td= "#{reminder.due_date.in_time_zone(reminder.site.time_zone).strftime("%a, %d %b")}"
        %td= reminder.remindees.map{|r| r.name}.join(", ")
        %td= "#{reminder.reminder1.in_time_zone(reminder.site.time_zone).strftime("%a, %d %b %l %p" )}"
#task-description
  =get_task_object(reminder.item_unit_task.task).description          

    

app/views/reminders/_reminder_form.html.haml
= simple_form_for(@reminder, remote: true, html: {class: "reminder-form form-horizontal"} ) do |f|
  %ul.errors
  .modal-body#reminder_form
    = f.input :frequency, collection: Reminder::FREQUENCY.sort.map {|k,v| [v,k]}, :selected => @reminder.try(:frequency_choice), label: "Frequency", 
      include_blank: false,  :input_html => {:class=> "frequency-select"}
      
    = f.input :due_date, as: :string,  placeholder: "Select due date", :input_html => { :class => 'datepicker', :id => "iut-#{iut.id}", 
       :value => @reminder.try(:due_date).try(:strftime,"%a, %d %b %Y")}, label: "Due Date:", :label_html => {:class => "due-date-label"}       
    
    = f.input :due_date, as: :hidden,    :input_html => { :class => 'due_date_alt'}    #this field sends date to controller
    
    //= f.text_field :due_date,  class: "datepicker" , id: "iu-#{iu.id}-task-#{task.id}", placeholder: "Select due date", as: :date_picker       
    //= f.input :remindees, as: :check_boxes, collection: @site.remindees, :item_wrapper_class => 'inline', label: "Choose recipients"
    //= f.association :remindees, as: :check_boxes, collection: @site.remindees, :input_html => { :id => "iu-#{iu.id}-task-#{task.id}" }
    
    = f.input :remindee_ids, as: :check_boxes, label: "Notify:",  :label_html => {:id => "notification-to"} do
      = f.collection_check_boxes :remindee_ids, @site.remindees, :id, :name do |b|
        = b.check_box(:id => "#{b.object.id}-iut-#{iut.id}" ) + b.label(:for => "#{b.object.id}-iut-#{iut.id}", :class => "reminder-checkbox-label" )
    
    = f.input :reminder1, collection: Reminder::REMIND_BEFORE.sort.map {|k,v| [v,k]}, :selected => @reminder.try(:reminder1_choice), label: "Send reminder", include_blank: false
    
    = f.input_field :item_unit_task_id, as: :hidden, 'value'=> iut.id
    //= f.input_field :task_id, as: :hidden, 'value'=> iut.task_id
  .modal-footer 
    = f.button :submit, value: "Save reminder", class:" btn btn-primary pull-right"  

app/views/reminders/_reminder_nav.html.haml
%ul.div.list-inline.pull-right.reminder-links{:id => "reminder-nav-#{reminder.id}"}
  %li
    = render 'reminders/state', reminder: reminder
  - if reminder.is_active?
    %li
      = link_to "Done", complete_reminder_history_path( reminder.id), remote: true, method: 'post', id: "reminder-complete"
      %sup
        %i.fa.fa-question.emphasis{"title"=>"click to mark task as complete"}
  %li   
    = link_to "Edit", edit_reminder_path(reminder), remote: true, id: "edit-reminder-link" 

app/views/reminders/_save.js.erb
$("ul.errors").html("")
<% if @reminder.errors.any? %> 
  <% @reminder.errors.full_messages.each do |msg| %>
        $("ul.errors").append($("<li />").html("<%= msg.html_safe %>"))
  <% end %>
<% else %>
  $('#reminder-unit-task-<%= iut.id %>').html("<%= j render 'reminders/reminder', iut: iut %>");
   $("#reminder_modal").modal("hide");
   $('#due-on-accordion-<%= iut.reminder.id %>').html("Due: <%= iut.reminder.due_date.strftime("%a, %-d %b")%>");  
<% end %>    

app/views/reminders/_state.html.haml
-if reminder.is_active?
  = link_to "Reminder Active", reminder_state_path(reminder), remote: true, method: "post" , id: "reminder-active", data:{ toggle: "tooltip", title: "Click to make reminder in-active" } 
  %sup
    %i.fa.fa-question.emphasis{"title"=>"Click to make reminder in-active"}
-else
  = link_to "Not Active", reminder_state_path(reminder), remote: true, method: "post" , id: "reminder-inactive"
  %sup
    %i.fa.fa-question.emphasis{"title"=>"Click to make reminder Active"}

app/views/reminders/complete.js.erb
$('#<%= @reminder.id %>.reminder-complete').html("<%= j render 'reminders/state' %>");

app/views/reminders/create.js.erb
<%= render "reminders/save", iut: @item_unit_task %>

app/views/reminders/edit.js.erb
//$('#reminder-unit-task-<%= @item_unit_task.id %>').html("<%= j render 'reminders/reminder_form', iut: @item_unit_task  %>");
$('#reminder_modal').html("<%= j render 'reminders/edit', iut: @item_unit_task  %>");
$('#reminder_modal').modal("show");

app/views/reminders/new.js.erb
$('#reminder_modal').html("<%= j render 'reminders/new', iut: @item_unit_task  %>");
$('#reminder_modal').modal("show");

app/views/reminders/state.js.erb
$('#reminder-nav-<%= @reminder.id %>').html("<%= j render 'reminders/reminder_nav', reminder: @reminder %>");

<% if @reminder.is_active? %>
$('#due-on-accordion-<%= @reminder.id %>').html("Due: <%= @reminder.due_date.strftime("%a, %-d %b")%>");
<% else %>
$('#due-on-accordion-<%= @reminder.id %>').html("");
<% end %>

app/views/reminders/update.js.erb
<%= render "reminders/save", iut: @item_unit_task %>