config/routes.rb
Maintr::Application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  as :user do
    get 'users/edit_password' => 'registrations#edit_password', :as => 'edit_user_password_registration'    
    patch 'users/:id' => 'registrations#update_password', :as => 'user_password_registration'            
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  

  root to: 'pages#front'
  get '/settings', to: 'settings#show'
  get '/dashboard', to: 'reminders#dashboard'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  get 'sites/remindee_option', to: 'sites#remindee_option'  #for the ajax request from sites form
  get '/confirm/:id', to: 'reminder_histories#url_redirect'
  match "/sms_back.json", to: 'reminder_histories#sms_back', via: [:get, :post], defaults: {format: 'json'}
  get '/dashboard_update', to: 'reminders#dashboard_update'  #for ajax call to update dashboard
  namespace :reminders do
    resources :items, only: [:index]
  end

  resources :sites do
    resources :items, only: [:index, :show, :destroy]

  end

  resources :item_units

  resources :custom_items, only: [:new, :create, :destroy]
  resources :custom_tasks, only: [:new, :create, :destroy]
  resources :remindees, only: [:new, :create, :edit, :update, :destroy]
  resources :reminders, only: [ :new, :create, :edit, :update] do
    post :state
  end

  resources :reminder_histories, only: [:index, :show], as: :histories
  get '/rh_events.json', to: 'reminder_histories#events', defaults: {format: 'json'}  #to pass reminder history data to calendar
  resources :reminder_histories,  only: [:show] do
    member do
      post :complete
      get :reminder_updated
      get :confirm
    end
  end

  
  
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  

end

app/models/item_unit.rb
class ItemUnit < ActiveRecord::Base

  belongs_to :item
  
  belongs_to :site
  has_many :item_unit_tasks, dependent: :destroy
  has_many :tasks, through: :item_unit_tasks

end

app/controllers/item_units_controller.rb
class ItemUnitsController < ApplicationController
  before_action :authenticate_user!

  before_action only: [:destroy] do
    if !(is_owner_of $current_site)
      flash[:error] = "You can't do that"
      redirect_to settings_path
    end
  end
  
  def new
    #this is not used.  instance variable created in items controller
    @item_unit = ItemUnit.new
    @item = Item.find_by_id(params[:item_id])
    #render partial 'new'

  end

  def show
    @item_unit = ItemUnit.find params[:id]
  end

  def create
    #binding.pry
      @item = Item.find_by_id(params[:item_unit][:item_id])
      @site = $current_site   #current site is a global variable
      #@site = Site.find_by_id(@item.site_id)
      @item_unit = ItemUnit.new(name: params[:item_unit][:name], item_id: params[:item_unit][:item_id], site_id: @site.id)
      #binding.pry
      
      respond_to do |format|
        if @item_unit.save
          if @item.itemable_type == 'SystemItem'
            SystemTask.where(system_item_id: get_item_object(@item).id).order(title: :asc).each do |st|
              task = Task.find_by(taskable: st)
              ItemUnitTask.create(item_unit_id: @item_unit.id, task_id: task.id)
            end
          end
          @item.reload
          format.html {redirect_to site_item_path(@site, @item)}
          format.js
        else
          flash[:error] = "Cannot take blank value"
          redirect_to :back
        end
      end
  end

  def destroy
    item_unit = get_item_unit
    @site = $current_site
    @item = item_unit.item
    item_unit.destroy
    #redirect_to site_item_path(site, item)

  end

  
  private

  def get_item_unit
    ItemUnit.find_by_id params[:id]
  end

  def get_site
    Site.find_by_id get_item_unit.site_id
  end

  

end

app/helpers/item_units_helper.rb
module ItemUnitsHelper
end

app/views/item_units/_all_item_units.html.haml
-item.item_units.where(site_id: site.id).each do |iu|
  =render 'item_units/item_unit', iu: iu

app/views/item_units/_item_unit.html.haml
=div_for(iu) do
  .well
    .col-md#unit-title
      .col-md-8.col-xs-8.text-left
        =link_to iu.name, item_unit_path(iu)
      .col-md-4.col-xs-4.text-right#item-unit-delete
        = link_to iu, method: :delete, remote: true do
          %i.fa.fa-times   
    .col-md.ul.accordion.list-group{id: "unit-#{iu.id}-tasks"}
      -iu.item.reload
      -iu.tasks.each do |task|
        =render 'item_units/task', iu: iu, task: task

    
#reminder_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}

app/views/item_units/_item_unit_form.html.haml
= simple_form_for(@item_unit, remote: true, html: { class: 'form-horizontal' }) do |f|
  %ul.errors
  .modal-body#item-unit-form
  = f.input :name, autofocus: true, wrapper: :horizontal_form, label: "Name"
  = f.input_field :item_id, as: :hidden, value: "#{@item.id}"
  .modal-footer
    = f.button :submit, value: "Add", class:" btn btn-primary pull-right"
    

app/views/item_units/_new.html.haml
.modal-dialog
  .modal-content.clearfix
    .modal-header.clearfix
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h4#myModalLabel.modal-title= "Adding a new unit for #{get_item_object(@item).name.titleize} "
    =render 'item_units/item_unit_form'  

app/views/item_units/_save.js.erb
$("ul.errors").html("")
<% if @item_unit.errors.any? %> 
  <% @item_unit.errors.full_messages.each do |msg| %>
        $("ul.errors").append($("<li />").html("<%= msg.html_safe %>"))
  <% end %>
<% else %>
  $('#item-units').html("<%= j render 'item_units/all_item_units', iu: @item_unit, site: @site, item: @item  %>");
$(".accordion").accordion({
    active: false,
    collapsible: true,
    heightStyle: "content"

  });
$('#new_item_unit_modal').modal("hide");
$('#new-task-link').html("<%= j(link_to "Add a task", new_custom_task_path(site_id: @site.id, item_id: @item.id), remote: true)  %>");

 
<% end %>    

app/views/item_units/_task.html.haml
%li.list-group-item
  - iut = get_item_unit_task iu.id, task.id      
  %h4
    =get_task_object(task).title.capitalize
    -if task.taskable_type == "CustomTask"
      =link_to custom_task_path(get_task_object(task), item_unit: iu), class: 'task-delete pull-right', 
      data: {confirm: "Are you sure?"}, method: :delete, remote: true do
        %i.fa.fa-times
    -if iut.reminder && iut.reminder.is_active?
      %span{:style=>"float:right", :id=>"due-on-accordion-#{iut.reminder.id}"}
        ="Due: #{iut.reminder.due_date.in_time_zone(iut.reminder.site.time_zone).strftime("%a, %-d %b")}"     

  .reminder{id: "reminder-unit-task-#{iut.id}"}
    - iut = get_item_unit_task(iu.id, task.id)
    - if iut.reminder
      =render 'reminders/reminder', iut: iut
    - else
      .col-md-8.task-description
        =get_task_object(iut.task).description
      .col-md-4
        = link_to  "Add Reminder", new_reminder_path(iut_id: iut.id), remote: true, class:'btn btn-primary pull-right'
        


app/views/item_units/create.js.erb
<%= render "item_units/save" %>

app/views/item_units/destroy.js.erb
$('#item-units').html("<%= j render 'item_units/all_item_units',  site: @site, item: @item  %>");
<% if @item.item_units.blank? %>
$('#new-task-link').html("");
<% end %>
$(".accordion").accordion({
    active: false,
    collapsible: true,
    heightStyle: "content"

  });

app/views/item_units/new.js.erb
$('#new_item_unit_modal').html("<%= j render 'item_units/new'  %>");
$('#new_item_unit_modal').modal("show");

app/views/item_units/show.html.haml
.container#item-units-page

  .col-md-10.col-md-offset-1
    %h4 
      = get_item_object(@item_unit.item).name + ": " + @item_unit.name
    .table-responsive.table-fixed
      %table.table
        %tbody
          %tr
            %td= "Warranty" 
            %td= "Attach document"
          %tr
            %td= "Warranty Expires" 
            %td= "May 23, 2016"
              