config/routes.rb
Maintr::Application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  as :user do
    get 'users/edit_password' => 'registrations#edit_password', :as => 'edit_user_password_registration'    
    patch 'users/:id' => 'registrations#update_password', :as => 'user_password_registration'            
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  

  root to: 'pages#front'
  get '/settings', to: 'settings#show'
  get '/dashboard', to: 'reminders#dashboard'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  get 'sites/remindee_option', to: 'sites#remindee_option'  #for the ajax request from sites form
  get '/confirm/:id', to: 'reminder_histories#url_redirect'
  match "/sms_back.json", to: 'reminder_histories#sms_back', via: [:get, :post], defaults: {format: 'json'}
  get '/dashboard_update', to: 'reminders#dashboard_update'  #for ajax call to update dashboard
  namespace :reminders do
    resources :items, only: [:index]
  end

  resources :sites do
    resources :items, only: [:index, :show, :destroy]

  end

  resources :item_units

  resources :custom_items, only: [:new, :create, :destroy]
  resources :custom_tasks, only: [:new, :create, :destroy]
  resources :remindees, only: [:new, :create, :edit, :update, :destroy]
  resources :reminders, only: [ :new, :create, :edit, :update] do
    post :state
  end

  resources :reminder_histories, only: [:index, :show], as: :histories
  get '/rh_events.json', to: 'reminder_histories#events', defaults: {format: 'json'}  #to pass reminder history data to calendar
  resources :reminder_histories,  only: [:show] do
    member do
      post :complete
      get :reminder_updated
      get :confirm
    end
  end

  
  
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :itemable, polymorphic: true
  belongs_to :site
  has_many :item_units, dependent: :destroy



end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :items, dependent: :destroy
  belongs_to :business_type
  has_many :item_units
  has_many :reminder_histories
  has_many :remindee_sites, dependent: :destroy
  has_many :remindees, through: :remindee_sites

  validates_presence_of :name, :business_type_id
  belongs_to :user
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :authenticate_user!
before_action :get_site
before_action :check_system_items_update

before_action only: [:index, :show] do
   if !(is_owner_of $current_site)
    flash[:error] = "You can't do that"
    redirect_to settings_path
  end
end

  def index
    @site = $current_site
    if @site  #if a user has a site(location) created else send to settings page
      
      @item = get_system_items(@site, "SystemItem").first   #system_items are entities that user cannot create or destroy
      setup_reminders_page
     
      render 'sites/items/index'
    else
      redirect_to settings_path
    end
  end

  def show
    @item = Item.find_by_id(params[:id])
    setup_reminders_page
    render 'sites/items/index'
  end

private

  def setup_reminders_page
    @site =  $current_site # from clicking site link_to on settings page
    
    @items = Item.where(site_id: @site.id)
    check_system_tasks_update @item if @item.itemable_type == "SystemItem"
      
    @item_unit = ItemUnit.new  #return an instance of item_unit to create a new unit
    @custom_item = CustomItem.new
    @custom_task = CustomTask.new
    @reminder = Reminder.new

  end

  

  def get_site
    
    $current_site = Site.find_by_id(params[:site_id])
    
        #Site.find_by_id(params[:site_id])
  end

  
  
  
  
  
end

app/controllers/reminders/items_controller.rb
class Reminders::ItemsController < ApplicationController
  before_action :authenticate_user!


  def index
    #come here when Reminder on the nav bar is clicked   

    @site = current_user.sites.first 
    @items = Item.all.where(site_id: @site.id)
    @item = Item.where(itemable_type: "SystemItem", site_id: @site.id).first
    #binding.pry
    render 'sites/items/index'
  end


end

app/controllers/sites/items_controller.rb
class Sites::ItemsController < ApplicationController
before_action :authenticate_user!

  def index
    #binding.pry
    @site = get_site(params[:format])  #params[:format] comes from clicking site link_to on settings page
    @items = Item.all.where(site_id: @site.id)
    @item = Item.where(itemable_type: "SystemItem", site_id: @site.id).first
    #binding.pry

  end

  def show
    #binding.pry
    @site = get_site(params[:site_id])
    @items = Item.all.where(site_id: site.id)
    @item = Item.find_by_id(params[:id])
    #binding.pry

  end

  private

  def get_site(id)
    if id == nil
      current_user.sites.first
    else
      Site.find_by_id(id)
      #binding.pry
    end
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :authenticate_user!
  around_filter :set_time_zone  #using gem browser_timezone_rails


  before_action only: [:destroy] do
    if !(is_owner_of get_site)
      flash[:error] = "You can't do that"
      redirect_to settings_path
    end
  end

  def new
    tz = ActiveSupport::TimeZone::MAPPING.key(Time.zone.name)  #converting tzinfo timezone names like "America/Los Angeles" to "Pacific Time"
    @site = Site.new(time_zone: tz)
  end

  def create
    
    name= params[:site][:name].downcase
    business_id = params[:site][:business_type_id]
    tz = params[:site][:time_zone]
    @site = Site.new(name: name, business_type_id: business_id, user: current_user, time_zone: tz)

    respond_to do |format|
      if @site.save
        SystemItem.where(business_type_id: business_id).order(name: :asc).each do |si|
          Item.create(itemable: si, site: @site)
        end
        if current_user.remindee_id.blank?
          remindee = Remindee.create(name: current_user.username, email: current_user.email)
          current_user.remindee_id = remindee.id
          current_user.phone = remindee.phone if current_user.phone.blank?
          current_user.save(validate: false)
          RemindeeSite.create(remindee_id: remindee.id, site_id: @site.id)  
        else
          RemindeeSite.create(remindee_id: current_user.remindee_id, site_id: @site.id)
        end
        format.html {redirect_to settings_path}
        format.js
      else
        flash[:error] = "Blank values not accepted"
        redirect_to settings_path
      end
    end
  end

  def destroy
    @site = get_site
    @site.destroy
    respond_to do |format|
      format.html { redirect_to settings_path}
      format.js
      
    end
    

  end

  def remindee_option
    name = params[:remindee_name]
    remindee = current_user.remindees.where(name: name)

    respond_to do |format|
      format.json {render json: {remindee: remindee}}
    end

  end

  private

  def get_site
    Site.find_by_id params[:id]
  end


  def set_time_zone
    old_time_zone = Time.zone
    Time.zone = browser_timezone if browser_timezone.present?
    
    yield
    ensure
      Time.zone = old_time_zone
  end
                                                                                 
  def browser_timezone
    cookies["browser.timezone"]
  end


end

app/helpers/reminders/items_helper.rb
module Reminders::ItemsHelper
end

app/helpers/sites/items_helper.rb
module Sites::ItemsHelper
end

app/views/sites/items/_item.html.haml
%li
  =div_for(item) do
    =link_to get_item_object(item).name.titleize , site_item_path(site, item), class:(make_active(site, item))  #make first system item active on reminders page load
    -if item.itemable_type == "CustomItem"
      =link_to custom_item_path(item), class: 'item-delete', data: {confirm: "Are you sure?"}, method: :delete do
        %i.fa.fa-times      

app/views/sites/items/_items_nav.html.haml
-items.each do |item|
  =render 'sites/items/item', item: item, site: site
    

app/views/sites/items/index.html.haml
#reminders-page.container
  .ul.nav.nav-pills.items-nav.col-md-8.col-md-offset-2#items-nav
    =render 'sites/items/items_nav', items: @items, site: @site
  .row
    .col-md-8.col-md-offset-2#location-display
      .location
        -if current_user.sites.count ==1
          .text-right#site-display
            = @site.name.titleize
        -else 
          =render 'sites/sites_dropdown'
  .row
    .col-md-8.col-md-offset-2#item-units
      =render 'item_units/all_item_units', item: @item, site: @site
  .row  
    .col-md-8.col-md-offset-2.row#item-units-links
      =link_to "Add new #{get_item_object(@item).name}", new_item_unit_path(item_id: @item.id), remote: true, id: "add-new-unit"
      #new-task-link
        -if !@item.item_units.blank?
          =link_to "Add a task", new_custom_task_path(site_id: @site.id, item_id: @item.id), remote: true

  #new_item_unit_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    

  #new_custom_item_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          %h4#myModalLabel.modal-title= "Add a new category"
        .modal-body
          = render 'custom_items/custom_item_form', modal: true
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close 

  #new_custom_task_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
