config/routes.rb
Maintr::Application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  as :user do
    get 'users/edit_password' => 'registrations#edit_password', :as => 'edit_user_password_registration'    
    patch 'users/:id' => 'registrations#update_password', :as => 'user_password_registration'            
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  

  root to: 'pages#front'
  get '/settings', to: 'settings#show'
  get '/dashboard', to: 'reminders#dashboard'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  get 'sites/remindee_option', to: 'sites#remindee_option'  #for the ajax request from sites form
  get '/confirm/:id', to: 'reminder_histories#url_redirect'
  match "/sms_back.json", to: 'reminder_histories#sms_back', via: [:get, :post], defaults: {format: 'json'}
  get '/dashboard_update', to: 'reminders#dashboard_update'  #for ajax call to update dashboard
  namespace :reminders do
    resources :items, only: [:index]
  end

  resources :sites do
    resources :items, only: [:index, :show, :destroy]

  end

  resources :item_units

  resources :custom_items, only: [:new, :create, :destroy]
  resources :custom_tasks, only: [:new, :create, :destroy]
  resources :remindees, only: [:new, :create, :edit, :update, :destroy]
  resources :reminders, only: [ :new, :create, :edit, :update] do
    post :state
  end

  resources :reminder_histories, only: [:index, :show], as: :histories
  get '/rh_events.json', to: 'reminder_histories#events', defaults: {format: 'json'}  #to pass reminder history data to calendar
  resources :reminder_histories,  only: [:show] do
    member do
      post :complete
      get :reminder_updated
      get :confirm
    end
  end

  
  
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  

end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :items, dependent: :destroy
  belongs_to :business_type
  has_many :item_units
  has_many :reminder_histories
  has_many :remindee_sites, dependent: :destroy
  has_many :remindees, through: :remindee_sites

  validates_presence_of :name, :business_type_id
  belongs_to :user
end

app/controllers/sites/items_controller.rb
class Sites::ItemsController < ApplicationController
before_action :authenticate_user!

  def index
    #binding.pry
    @site = get_site(params[:format])  #params[:format] comes from clicking site link_to on settings page
    @items = Item.all.where(site_id: @site.id)
    @item = Item.where(itemable_type: "SystemItem", site_id: @site.id).first
    #binding.pry

  end

  def show
    #binding.pry
    @site = get_site(params[:site_id])
    @items = Item.all.where(site_id: site.id)
    @item = Item.find_by_id(params[:id])
    #binding.pry

  end

  private

  def get_site(id)
    if id == nil
      current_user.sites.first
    else
      Site.find_by_id(id)
      #binding.pry
    end
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :authenticate_user!
  around_filter :set_time_zone  #using gem browser_timezone_rails


  before_action only: [:destroy] do
    if !(is_owner_of get_site)
      flash[:error] = "You can't do that"
      redirect_to settings_path
    end
  end

  def new
    tz = ActiveSupport::TimeZone::MAPPING.key(Time.zone.name)  #converting tzinfo timezone names like "America/Los Angeles" to "Pacific Time"
    @site = Site.new(time_zone: tz)
  end

  def create
    
    name= params[:site][:name].downcase
    business_id = params[:site][:business_type_id]
    tz = params[:site][:time_zone]
    @site = Site.new(name: name, business_type_id: business_id, user: current_user, time_zone: tz)

    respond_to do |format|
      if @site.save
        SystemItem.where(business_type_id: business_id).order(name: :asc).each do |si|
          Item.create(itemable: si, site: @site)
        end
        if current_user.remindee_id.blank?
          remindee = Remindee.create(name: current_user.username, email: current_user.email)
          current_user.remindee_id = remindee.id
          current_user.phone = remindee.phone if current_user.phone.blank?
          current_user.save(validate: false)
          RemindeeSite.create(remindee_id: remindee.id, site_id: @site.id)  
        else
          RemindeeSite.create(remindee_id: current_user.remindee_id, site_id: @site.id)
        end
        format.html {redirect_to settings_path}
        format.js
      else
        flash[:error] = "Blank values not accepted"
        redirect_to settings_path
      end
    end
  end

  def destroy
    @site = get_site
    @site.destroy
    respond_to do |format|
      format.html { redirect_to settings_path}
      format.js
      
    end
    

  end

  def remindee_option
    name = params[:remindee_name]
    remindee = current_user.remindees.where(name: name)

    respond_to do |format|
      format.json {render json: {remindee: remindee}}
    end

  end

  private

  def get_site
    Site.find_by_id params[:id]
  end


  def set_time_zone
    old_time_zone = Time.zone
    Time.zone = browser_timezone if browser_timezone.present?
    
    yield
    ensure
      Time.zone = old_time_zone
  end
                                                                                 
  def browser_timezone
    cookies["browser.timezone"]
  end


end

app/helpers/sites/items_helper.rb
module Sites::ItemsHelper
end

app/views/sites/_my_sites.html.haml
=div_for(site) do
  .well.col-md.col-xs.site
    #site-name
      =link_to site.name.titleize, site_items_path(site_id: site.id)
      = link_to site, class: 'site-delete pull-right', method: :delete, remote: true do
        %i.fa.fa-times  
    = render 'remindees/remindees', site: site
    #remindee-form-link
      = link_to  "Add Recipient", new_remindee_path(site_id: site.id), remote: true  



#remindee_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  

app/views/sites/_new.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h4#myModalLabel.modal-title= "Adding a location"
    =render 'sites/site_form'  

app/views/sites/_save.js.erb
$("ul.errors").html("")
<% if @site.errors.any? %> 
  <% @site.errors.full_messages.each do |msg| %>
        $("ul.errors").append($("<li />").html("<%= msg.html_safe %>"))
  <% end %>
<% else %>
  $('#sites').append("<%= j render 'sites/my_sites', site: @site  %>");
   $("#new_site_modal").modal("hide")  
<% end %>    

app/views/sites/_site_form.html.haml
= simple_form_for(@site, remote: true,  html: { class: 'form-horizontal' }) do |f|
  %ul.errors
  .modal-body#site-form
    = f.input :name, autofocus: true, wrapper: :horizontal_form, label: "Location Name"
    = f.association :business_type, wrapper: :horizontal_form
    = f.input :time_zone, collection: ActiveSupport::TimeZone::MAPPING.keys, :selected => ActiveSupport::TimeZone::MAPPING.key(Time.zone.name),
     priority: /US/, label: "Time Zone",  include_blank: false,  :input_html => {:id=> "time-zone-select"}, wrapper: :horizontal_form
  .modal-footer
    = f.button :submit, value: "Add Location", class:" btn btn-primary pull-right" 

app/views/sites/_sites_dropdown.html.haml
.dropdown.pull-right
  %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button", :id=>"site-display"}
    = $current_site.name.titleize
    %span.caret
  %ul.dropdown-menu{:role => "menu"}
    - current_user.sites.each do |site|
      %li
        =link_to site.name.titleize, site_items_path(site.id)

app/views/sites/create.js.erb
<%= render "sites/save" %>

app/views/sites/destroy.js.erb
$('#site_<%= @site.id %>').remove();

app/views/sites/new.js.erb
$('#new_site_modal').html("<%= j render 'sites/new'  %>");
$('#new_site_modal').modal("show");